package game

// GENERATED by tools/gen/gen_qr.py; do not edit. A QR code (version 3, level M, mask 2) for
//   https://thegrumpygamedev.itch.io/
// One u32 per row, top to bottom; bit x (from the least significant) is column x; 1 is a dark module.

QR_SIZE :: 29
QR_URL :: "https://thegrumpygamedev.itch.io/"

QR_ROWS :: [QR_SIZE]u32 {
	0x1FDD967F,
	0x10401641,
	0x1751475D,
	0x17431D5D,
	0x1758E95D,
	0x1053F941,
	0x1FD5557F,
	0x0014B300,
	0x07C6C87D,
	0x11DF9736,
	0x00B20C74,
	0x0BF54DB9,
	0x060A08D6,
	0x11DEE439,
	0x0795F5C5,
	0x09813292,
	0x06024BD6,
	0x15F80495,
	0x0551945D,
	0x081D5A89,
	0x1DF21049,
	0x1F157900,
	0x075FE07F,
	0x0118BD41,
	0x0DF2555D,
	0x1E0F0B5D,
	0x0FD4975D,
	0x0B3D7041,
	0x07AE417F,
}
