package game

// Sprites of the tile sheet (assets/images/tiles.png), translated from config/sprites.json. `name` is the JSON key;
// a test compares every entry with the original file while it is still in the repo.

Sprite_Id :: enum u8 {
	Floor_Tile,
	Wall_Tile_N,
	Wall_Tile_E,
	Wall_Tile_NE,
	Wall_Tile_S,
	Wall_Tile_NS,
	Wall_Tile_ES,
	Wall_Tile_NES,
	Wall_Tile_W,
	Wall_Tile_NW,
	Wall_Tile_EW,
	Wall_Tile_NEW,
	Wall_Tile_SW,
	Wall_Tile_NSW,
	Wall_Tile_ESW,
	Wall_Tile_NESW,
	Hunter_Creature,
	Key_Item,
	NS_Door,
	EW_Door,
	Dither,
	Exit,
	Diamond_Item,
	Zombie_Creature,
	Exit_Key_Item,
	Health_Bar_10,
	Health_Bar_20,
	Health_Bar_30,
	Health_Bar_40,
	Health_Bar_50,
	Health_Bar_60,
	Health_Bar_70,
	Health_Bar_80,
	Health_Bar_90,
	Health_Bar_100,
	Potion_Item,
	Sword_Item,
	Move_Icon,
	Shield_Item,
	Unexplored,
	Attack_Upgrade,
	Armor_Upgrade,
	Health_Upgrade,
	Trap_Item,
	Miniboss_Creature,
	Bombs,
}

Sprite :: struct {
	name:          string,
	image:         Image_Id,
	x, y, w, h:        int,
	offset_x, offset_y: int, // added to the draw position (the health bars sit 4 pixels above their cell)
}

SPRITES :: [Sprite_Id]Sprite {
	.Floor_Tile = {name = "FloorTile", image = .Tiles, x = 0, y = 0, w = 16, h = 16},
	.Wall_Tile_N = {name = "WallTileN", image = .Tiles, x = 16, y = 0, w = 16, h = 16},
	.Wall_Tile_E = {name = "WallTileE", image = .Tiles, x = 32, y = 0, w = 16, h = 16},
	.Wall_Tile_NE = {name = "WallTileNE", image = .Tiles, x = 48, y = 0, w = 16, h = 16},
	.Wall_Tile_S = {name = "WallTileS", image = .Tiles, x = 64, y = 0, w = 16, h = 16},
	.Wall_Tile_NS = {name = "WallTileNS", image = .Tiles, x = 80, y = 0, w = 16, h = 16},
	.Wall_Tile_ES = {name = "WallTileES", image = .Tiles, x = 96, y = 0, w = 16, h = 16},
	.Wall_Tile_NES = {name = "WallTileNES", image = .Tiles, x = 112, y = 0, w = 16, h = 16},
	.Wall_Tile_W = {name = "WallTileW", image = .Tiles, x = 0, y = 16, w = 16, h = 16},
	.Wall_Tile_NW = {name = "WallTileNW", image = .Tiles, x = 16, y = 16, w = 16, h = 16},
	.Wall_Tile_EW = {name = "WallTileEW", image = .Tiles, x = 32, y = 16, w = 16, h = 16},
	.Wall_Tile_NEW = {name = "WallTileNEW", image = .Tiles, x = 48, y = 16, w = 16, h = 16},
	.Wall_Tile_SW = {name = "WallTileSW", image = .Tiles, x = 64, y = 16, w = 16, h = 16},
	.Wall_Tile_NSW = {name = "WallTileNSW", image = .Tiles, x = 80, y = 16, w = 16, h = 16},
	.Wall_Tile_ESW = {name = "WallTileESW", image = .Tiles, x = 96, y = 16, w = 16, h = 16},
	.Wall_Tile_NESW = {name = "WallTileNESW", image = .Tiles, x = 112, y = 16, w = 16, h = 16},
	.Hunter_Creature = {name = "HunterCreature", image = .Tiles, x = 0, y = 32, w = 16, h = 16},
	.Key_Item = {name = "KeyItem", image = .Tiles, x = 16, y = 32, w = 16, h = 16},
	.NS_Door = {name = "NSDoor", image = .Tiles, x = 32, y = 32, w = 16, h = 16},
	.EW_Door = {name = "EWDoor", image = .Tiles, x = 48, y = 32, w = 16, h = 16},
	.Dither = {name = "Dither", image = .Tiles, x = 64, y = 32, w = 16, h = 16},
	.Exit = {name = "Exit", image = .Tiles, x = 80, y = 32, w = 16, h = 16},
	.Diamond_Item = {name = "DiamondItem", image = .Tiles, x = 96, y = 32, w = 16, h = 16},
	.Zombie_Creature = {name = "ZombieCreature", image = .Tiles, x = 112, y = 32, w = 16, h = 16},
	.Exit_Key_Item = {name = "ExitKeyItem", image = .Tiles, x = 0, y = 48, w = 16, h = 16},
	.Health_Bar_10 = {name = "HealthBar10", image = .Tiles, x = 16, y = 48, w = 16, h = 4, offset_y = -4},
	.Health_Bar_20 = {name = "HealthBar20", image = .Tiles, x = 16, y = 52, w = 16, h = 4, offset_y = -4},
	.Health_Bar_30 = {name = "HealthBar30", image = .Tiles, x = 16, y = 56, w = 16, h = 4, offset_y = -4},
	.Health_Bar_40 = {name = "HealthBar40", image = .Tiles, x = 32, y = 48, w = 16, h = 4, offset_y = -4},
	.Health_Bar_50 = {name = "HealthBar50", image = .Tiles, x = 32, y = 52, w = 16, h = 4, offset_y = -4},
	.Health_Bar_60 = {name = "HealthBar60", image = .Tiles, x = 32, y = 56, w = 16, h = 4, offset_y = -4},
	.Health_Bar_70 = {name = "HealthBar70", image = .Tiles, x = 32, y = 60, w = 16, h = 4, offset_y = -4},
	.Health_Bar_80 = {name = "HealthBar80", image = .Tiles, x = 48, y = 48, w = 16, h = 4, offset_y = -4},
	.Health_Bar_90 = {name = "HealthBar90", image = .Tiles, x = 48, y = 52, w = 16, h = 4, offset_y = -4},
	.Health_Bar_100 = {name = "HealthBar100", image = .Tiles, x = 48, y = 56, w = 16, h = 4, offset_y = -4},
	.Potion_Item = {name = "PotionItem", image = .Tiles, x = 48, y = 64, w = 16, h = 16},
	.Sword_Item = {name = "SwordItem", image = .Tiles, x = 0, y = 64, w = 16, h = 16},
	.Move_Icon = {name = "MoveIcon", image = .Tiles, x = 16, y = 64, w = 16, h = 16},
	.Shield_Item = {name = "ShieldItem", image = .Tiles, x = 64, y = 64, w = 16, h = 16},
	.Unexplored = {name = "Unexplored", image = .Tiles, x = 64, y = 48, w = 16, h = 16},
	.Attack_Upgrade = {name = "AttackUpgrade", image = .Tiles, x = 80, y = 48, w = 16, h = 16},
	.Armor_Upgrade = {name = "ArmorUpgrade", image = .Tiles, x = 96, y = 48, w = 16, h = 16},
	.Health_Upgrade = {name = "HealthUpgrade", image = .Tiles, x = 112, y = 48, w = 16, h = 16},
	.Trap_Item = {name = "TrapItem", image = .Tiles, x = 32, y = 64, w = 16, h = 16},
	.Miniboss_Creature = {name = "MinibossCreature", image = .Tiles, x = 80, y = 64, w = 16, h = 16},
	.Bombs = {name = "Bombs", image = .Tiles, x = 96, y = 64, w = 16, h = 16},
}
